Prevent #53 issue
fatal error: unexpectedly found nil while unwrapping an Optional value
is caused by an unretained _self when entering the method. Temporary
solving the issue removing the weak keyword.

Warning: possible leak